#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
解析 dm.h 中全部 DM_CALL/DM_API dm_* 导出函数，生成:
  1) tests/test_dm_all.cpp  -- 每函数独立调用的冒烟测试 (接受 argv[1]=index)
  2) tests/smoke_funcs.txt  -- 与上面顺序一致的函数名列表 (供驱动按序调用)

设计要点 (隔离崩溃 + ABI 安全):
- 每个函数在其自有子进程中调用 (由 run_smoke.py 循环驱动), 单个函数硬崩溃不影响其他函数。
- typedef 返回类型统一为 long (返回值被忽略; 整数/指针返回在 RAX, 不影响)。
- 指针参数: 基元指针 (char*/wchar_t*/unsigned char*/long* 等) 保留精确类型并传 (T*)g_out;
  未知 struct/class 指针归一为 void* 传 (void*)g_out (指针->指针, ABI 等价)。
- float/double 保留类型传 0.0f/0.0; 其余整数型传 0。
- 每个调用以 __try/__except 守护, 输出 "name,RESULT,detail" 一行。
"""
import re
import os

SRC = "D:/dm/dm_hook/dm.h"
OUT_CPP = "D:/dm/dm_hook/tests/test_dm_all.cpp"
OUT_LIST = "D:/dm/dm_hook/tests/smoke_funcs.txt"
DLL_PATH = "D:/dm/dm_hook/build/dm_hook.dll"

PRIMITIVE_PTR = {
    "char", "wchar_t", "unsigned char", "signed char", "long", "int",
    "short", "unsigned long", "unsigned int", "unsigned short",
    "float", "double", "bool", "size_t", "intptr_t", "DWORD",
    "HWND", "HANDLE", "BOOL", "BYTE", "WORD", "char16_t", "void",
}

INT_TYPES = {"long", "int", "short", "unsigned long", "unsigned int",
             "unsigned short", "bool", "size_t", "intptr_t", "DWORD",
             "HWND", "HANDLE", "BOOL", "BYTE", "WORD"}


def split_type_name(param):
    """把 'const char* x' / 'long hwnd' / 'char*' 拆成 (type, name)。"""
    toks = param.split()
    if (len(toks) >= 2 and re.match(r'^[A-Za-z_]\w*$', toks[-1])
            and '*' not in toks[-1] and '&' not in toks[-1]):
        return (' '.join(toks[:-1]), toks[-1])
    return (' '.join(toks), '')


def classify_arg(param):
    typ, _name = split_type_name(param)
    base = typ.strip()
    is_const = base.startswith("const ") or " const " in (" " + base + " ")
    base = base.replace("const", "").strip()
    if base.endswith("*"):
        pointee = base[:-1].strip()
        if pointee == "char":
            return ("const char*" if is_const else "char*",
                    '""' if is_const else "(char*)g_out")
        if pointee == "wchar_t":
            return ("const wchar_t*" if is_const else "wchar_t*",
                    'L""' if is_const else "(wchar_t*)g_wbuf")
        if pointee == "void":
            return ("void*", "(void*)g_out")
        if pointee in PRIMITIVE_PTR:
            return (base, "(%s)g_out" % base)
        # 未知 struct/class 指针 -> 归一 void*
        return ("void*", "(void*)g_out")
    if base == "float":
        return ("float", "0.0f")
    if base == "double":
        return ("double", "0.0")
    return (base, "0")


def parse_decls(txt):
    # 匹配 DM_CALL/DM_API 导出:  RET dm_name ( args );
    pat = re.compile(
        r"(DM_CALL|DM_API)\s+([A-Za-z_][\w]*)\s*\(([^;]*?)\)\s*;",
        re.DOTALL)
    out = []
    seen = set()
    for m in pat.finditer(txt):
        ret, name, args = None, m.group(2), m.group(3)
        if not name.startswith("dm_"):
            continue
        if name in seen:
            continue
        seen.add(name)
        arg_str = args.strip()
        if arg_str == "" or arg_str == "void":
            params = []
        else:
            # 拆分顶层逗号 (不考虑函数指针嵌套, 本 API 没有)
            parts = [p.strip() for p in arg_str.split(",") if p.strip()]
            params = []
            for p in parts:
                # 形如 "long x" / "const char* y" ; 取类型部分
                toks = p.split()
                # 去掉参数名: 最后一段若不是类型则去掉
                typ = p
                params.append(classify_arg(typ))
        out.append((name, params))
    return out


def main():
    with open(SRC, "r", encoding="utf-8", errors="replace") as f:
        txt = f.read()
    decls = parse_decls(txt)
    decls.sort(key=lambda d: d[0])
    print("parsed dm_* functions:", len(decls))

    lines = []
    lines.append("// tests/test_dm_all.cpp")
    lines.append("// AUTO-GENERATED by gen_smoke.py -- 每函数独立调用 (argv[1]=index)")
    lines.append("#include <windows.h>")
    lines.append("#include <cstdio>")
    lines.append("#include <cstdint>")
    lines.append("#define DM_CALL __stdcall")
    lines.append("")
    lines.append("static char g_out[4096];")
    lines.append("static wchar_t g_wbuf[2048];")
    lines.append("")
    lines.append("typedef long (DM_CALL* FnT)(void);")
    lines.append("")

    # 每个函数一个 tester 函数
    for i, (name, params) in enumerate(decls):
        arg_types = ", ".join(t for t, _ in params) if params else "void"
        call_args = ", ".join(a for _, a in params)
        lines.append("static void T%d(HMODULE h) {" % i)
        lines.append('    typedef long (DM_CALL* Fn)(%s);' % arg_types)
        lines.append('    Fn p = (Fn)GetProcAddress(h, "%s");' % name)
        lines.append('    if (!p) { printf("%s,MISSING,\\n"); return; }' % name)
        lines.append("    __try {")
        lines.append("        p(%s);" % call_args)
        lines.append('        printf("%s,OK,\\n");' % name)
        lines.append("    } __except(EXCEPTION_EXECUTE_HANDLER) {")
        lines.append('        printf("%s,CRASH,%%lu\\n", GetExceptionCode());' % name)
        lines.append("    }")
        lines.append("}")
        lines.append("")

    lines.append("typedef void (*Tester)(HMODULE);")
    lines.append("static Tester g_tbl[] = {")
    for i in range(len(decls)):
        lines.append("    T%d," % i)
    lines.append("};")
    lines.append("static const int g_n = %d;" % len(decls))
    lines.append("")
    lines.append("int main(int argc, char** argv) {")
    lines.append('    int idx = (argc > 1) ? atoi(argv[1]) : -1;')
    lines.append('    HMODULE h = LoadLibraryA("%s");' % DLL_PATH)
    lines.append('    if (!h) { printf("LOAD_FAIL,%lu\\n", GetLastError()); return 1; }')
    lines.append("    if (idx < 0 || idx >= g_n) { printf(\"BAD_IDX\\n\"); return 2; }")
    lines.append("    g_tbl[idx](h);")
    lines.append("    return 0;")
    lines.append("}")
    lines.append("")

    with open(OUT_CPP, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    with open(OUT_LIST, "w", encoding="utf-8") as f:
        for name, _ in decls:
            f.write(name + "\n")
    print("written:", OUT_CPP, "| funcs:", len(decls))


if __name__ == "__main__":
    main()
